### ISSUE TITLE
Add tests for backward mode AD.

### ISSUE THREAD

**Issue by trappmartin** [phipsgabler/DynamicComputationGraphs.jl#2]
Todo:
- [ ] Add unit tests for elementary functions.
- [ ] Add tests for composite functions using finite differences.

**Comment by phipsgabler** [comment]
That's a good one -- do you know of any test sets with reference derivatives?  I wanted to include [DiffTests.jl](https://github.com/JuliaDiff/DiffTests.jl/blob/05b8721dd0dabc62ee5ba39077ed4b27163ec45e/src/DiffTests.jl), but they don't provide the analytical derivatives.  Or is it just good practice to compare with finite differences?  

Other than that, I'm proably going to take something from Flux.Trackers tests.

**Comment by trappmartin** [comment]
I think comparing with finite differences is a good practice. ForwardDiff.jl seems to use Calculus.jl for that purpose.

Maybe make some test for elementary functions and then add tests using DiffTests.jl and finite differences.
