### ISSUE TITLE
Corner Cases

### ISSUE THREAD

**Issue by trappmartin** [phipsgabler/DynamicComputationGraphs.jl#4]
Here are a few corner cases which we should support.

- [ ] stochastic and deterministic `For` loops i.e., `K ~ ...; for k in 1:K`
- [ ] stochastic and deterministic While loops
- [ ] stochastic and deterministic `If-Else` conditions 
- [ ] stochastic and deterministic statements / assignments
- [ ] model recursions / compositional models
- [ ] recursions in general

**Comment by phipsgabler** [comment]
Moved to Readme under "Project Goals"
