### ISSUE TITLE
Literature 

### ISSUE THREAD

**Issue by yebai** [phipsgabler/DynamicComputationGraphs.jl#5]
The following paper provides an excellent introduction to AutoDiff and related algorithms. 

- Griewank, A., & Walther, A. (2008). Evaluating derivatives: principles and techniques of algorithmic differentiation (Vol. 105). Siam.

**Comment by phipsgabler** [comment]
Oh yes, thanks -- I also stumbled upon it just a few days ago. Really detailed!
